#!/usr/bin/env python
#
# Copyright 2014 Cyril Plisko. All rights reserved.
# Use is subject to license terms.
#

import sys
import izdb

if __name__ == "__main__":
    try:
        sys.exit(izdb.main(sys.argv))
    except KeyboardInterrupt:
        pass
